### PR TITLE
L5 Alterations

### PR DESCRIPTION
**Pull request by memco**
In addition to the composer updates in #93, I found the following changes necessary to work with L5.  This is the bare minimum of stuff I found I needed to get this working on L5.  May not be the cleanest route, but it was the best I could figure so far.

### CODE REVIEW

**Comment by freekmurze** [comment]
Why have you closed this pull request? Are you giving up on making the package L5 compatible? Seems like you were on the right track.

**Comment by memco** [comment]
No, I'm not giving up, I just was having a lot of trouble with the tests, so I closed it until I could get those passing.  

At first I was relying on Travis' build errors because I couldn't get the tests to run locally, but I've solved that and will finish up testing locally before I push and reopen.  This may have to wait until Monday, but I'll try my best to have it done sooner.

**Comment by memco** [comment]
As a note, this PR *technically* works in that if you pull in my L5 branch you should be able to instantiate a menu and render it.  However, the changes made to config settings have at least broken the tests and until I fix those, I don't really know what might be broken behind the scenes that may cause unexpected output.

**Comment by freekmurze** [comment]
Ok! Thanks for your work!

**Comment by memco** [comment]
Ok, cleared up the remaining issues and this should be green.  Sorry for the bevy of changes earlier I didn't realize how much else needed to be changed to get this properly working on L5.  This is one of my first major pull requests to a repo so I hope this looks ok.

**Comment by freekmurze** [comment]
Nice one! Hopefully this gets pulled and tagged soon!

**Comment by vespakoen** [comment]
Thanks a lot!!

**Pull request merged**
