### PR TITLE
Add Laravel 5 support

### PR DESCRIPTION
**Pull request by freekmurze**

### CODE REVIEW

**Comment by vespakoen** [comment]
Build is failing, can you check what's going on / send a fix?

**Comment by freekmurze** [comment]
It seems that your tests are using deprecated assertions methods:

```
There was 1 error:
1) ItemListTest::testCanCreateListsOfADifferentElement
ErrorException: PHPUnit_Framework_Assert::assertTag is deprecated
/home/travis/build/freekmurze/menu/tests/_start.php:136
/home/travis/build/freekmurze/menu/tests/ItemListTest.php:20
                                   
FAILURES!                          
Tests: 2, Assertions: 1, Errors: 1.
The command "phpunit" exited with 2.
```

**Comment by freekmurze** [comment]
I left the existing tested untouched and fixed the problem by requiring a version of phpunit where assertTag wasn't yet deprecated.

**Comment by vespakoen** [comment]
Great, thanks a lot!!

**Pull request merged**
